/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class RaizCuadrada */

#ifndef _Included_RaizCuadrada
#define _Included_RaizCuadrada
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     RaizCuadrada
 * Method:    raizc
 * Signature: (D)D
 */
JNIEXPORT jdouble JNICALL Java_RaizCuadrada_raizc
  (JNIEnv *, jobject, jdouble);

#ifdef __cplusplus
}
#endif
#endif
