/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.tec.ic6821.jdbc;

import edu.tec.ic6821.jdbc.users.PGUserDao;
import edu.tec.ic6821.jdbc.model.User;
import edu.tec.ic6821.jdbc.users.UserDao;

import java.util.List;
import java.util.Optional;

public class App {
    public static void main(String[] args) {

        ApplicationProperties properties = new ApplicationProperties();

        UserDao userDao = new PGUserDao(properties);

        User user = new User("username1", "name1");
        Optional<User> createdUser = userDao.create(user);

        System.out.println("createdUser.get() = " + createdUser.get());

        User user2 = new User("username2", "name2");
        userDao.create(user2);
        User user3 = new User("username3", "name3");
        userDao.create(user3);
        User user4 = new User("username4", "name4");
        userDao.create(user4);

        final List<User> users = userDao.findAll();
        users.forEach(System.out::println);

    }
}
