/*
 * This source file was generated by the Gradle 'init' task
 */
package org.figures;

import java.util.List;

public final class App {

    public static void main(String[] args) {
        App app = new App();
        Scene scene = app.buildScene();
        scene.draw(new DefaultCanvas());
    }

    private Scene buildScene() {
        Figure triangle = new Triangle(
                new DefaultColorable(new Color("#e5f342"), new Color("#ffffff")),
                new DefaultPositionable(new Point(23.2, 15.1)),
                100.0
        );

        Figure square = new Square(
                new DefaultColorable(new Color("#e5f342"), new Color("#ffffff")),
                new DefaultPositionable(new Point(12.2, 17.9)),
                150.0
        );

        return new DefaultScene(List.of(triangle, square));
    }

}
